Pandas and Numpy need to be loaded as packages using import statements

import pandas as pd
import numpy as np

ideally upon installing anaconda these packages should be automatically loaded. just like jupyter.
in case there are issues, please follow the below steps

left click Windows Start ==> on the applications pane ==> click on anaconda ==> click on anaconda prompt ==> in the prompt type 
===> conda install pandas==> pandas will get installed

===> conda install numpy  ===> numpy will get installed




In [2]:
import pandas as pd

In [3]:
import numpy as np

### Let us create different python objects



In [9]:
##### new list called  "labels" with strings
labels = ['a','b','c','d','e']

In [10]:
#### create a new list of numbers
my_data = [10,20,30,40,50]

In [11]:
#### create a new numpy array
myarr = np.array(my_data)

In [15]:
### create a dictionary
mydict = {'key1':10, 'key2':20, 'key3':100,'key4':40,'key5':50}

In [17]:
### print everything
print(labels)
print(my_data)
print(myarr)
print(mydict)

['a', 'b', 'c', 'd', 'e']
[10, 20, 30, 40, 50]
[10 20 30 40 50]
{'key1': 10, 'key2': 20, 'key3': 100, 'key4': 40, 'key5': 50}


In [18]:
### create a new series
### series takes a lot of parameters. but we will ONLY focus on parameters called "data" and "index"


In [21]:
## method 1 - create a series out of a list my_data
pd.Series(data=my_data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [23]:
### create a series with "data " parametre from  my_data list and we want to change the index parameter using "labels" list
my_series = pd.Series(data=my_data,index=labels)
print(my_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [27]:
### another way of creating a series
my_series1 = pd.Series(my_data,labels)
print(my_series1)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [29]:
### create a series from a tuple
## create my_tup
my_tup = ((1,2),('aa','bb'),(3,4),('cc','dd'),(50,60))
my_tup_series = pd.Series(data=my_tup,index=labels)
print(my_tup_series)

a      (1, 2)
b    (aa, bb)
c      (3, 4)
d    (cc, dd)
e    (50, 60)
dtype: object


In [31]:
my_tup = ((1,2),('aa','bb'),(3,4),('cc','dd'))
my_tup_series1 = pd.Series(data=my_tup,index=labels)
print(my_tup_series)

### indexes and contents need to align/match

ValueError: Length of passed values is 4, index implies 5

In [33]:
## create a series by using numpy array and labeled index 
my_ser3 = pd.Series(data=myarr,index=labels)
print(my_ser3)

a    10
b    20
c    30
d    40
e    50
dtype: int32


In [34]:
###
my_ser4 = pd.Series(myarr)
print(my_ser4)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [37]:
### create a series from a dictionary
mydict

mylabel = ['python','scala','java','c++','cobol']

print(mydict)
print(mylabel)

{'key1': 10, 'key2': 20, 'key3': 100, 'key4': 40, 'key5': 50}
['python', 'scala', 'java', 'c++', 'cobol']


In [38]:
my_series_5 = pd.Series(data=mydict)
print(my_series_5)

key1     10
key2     20
key3    100
key4     40
key5     50
dtype: int64


In [40]:
my_series_6 = pd.Series(data=mydict,index=mylabel)
print(my_series_6)

python   NaN
scala    NaN
java     NaN
c++      NaN
cobol    NaN
dtype: float64


In [41]:
mylabel 

['python', 'scala', 'java', 'c++', 'cobol']

In [46]:
mylabel[4] = 'key5'

In [47]:
mylabel

['python', 'scala', 'java', 'c++', 'key5']

In [48]:
my_series_7 = pd.Series(data=mydict,index=mylabel)
print(my_series_7)

python     NaN
scala      NaN
java       NaN
c++        NaN
key5      50.0
dtype: float64


### Getting data from Series

In [49]:
myseries_8 = pd.Series(data=[1,2,3,4],index=['dog','cat','cow','pig'])

### data is 1,2,3,4 and index is dog, cat, cow and pig

In [50]:
print(myseries_8)

dog    1
cat    2
cow    3
pig    4
dtype: int64


In [54]:
myseries_9 = pd.Series(data=[100,200,300,400,399,599,199],index=['indx1','indx2','indx3','indx4','indx5','indx6','indx7'])
print(myseries_9)

indx1    100
indx2    200
indx3    300
indx4    400
indx5    399
indx6    599
indx7    199
dtype: int64


In [55]:
myseries_9['indx6']

599

In [56]:
myseries_9[5]

599

In [57]:
### create numpy array with country names
np_country = np.array(['china','india','senegal','tanzania','nigeria','costa rica','fiji','samoa','indonesia','germany'])

In [59]:
### create a series with np_country
series_country = pd.Series(data=np_country)
print(series_country)

0         china
1         india
2       senegal
3      tanzania
4       nigeria
5    costa rica
6          fiji
7         samoa
8     indonesia
9       germany
dtype: object


In [60]:
### create an array of labels
np_country_labels = np.array(['lab1','lab2','lab3','lab4','lab5','lab6','lab7','lab8','lab9','lab10'])

In [62]:
## create a new series with labels
series_country1 = pd.Series(data=np_country, index=np_country_labels)
print(series_country1)

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object


In [63]:
###alternate ways of accessing data from a series
print(series_country1.loc['lab1'])

china


In [65]:
print(series_country1['lab1'])

china


In [67]:
print(series_country1[0])

china


In [68]:
print(series_country1.iloc[0])

china


### SCALAR SERIES


In [70]:
series_scalar = pd.Series(data=500,index=['a','b','c','d'])
print(series_scalar)

a    500
b    500
c    500
d    500
dtype: int64


In [71]:
series_country1

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object

In [72]:
series_country1['lab1':'lab3']

lab1      china
lab2      india
lab3    senegal
dtype: object

In [73]:
series_country1.loc['lab1':'lab3']

lab1      china
lab2      india
lab3    senegal
dtype: object

In [75]:
series_country1.iloc[0:3]

lab1      china
lab2      india
lab3    senegal
dtype: object

In [77]:
series_country1[['lab1','lab3']]

### extracting using comma notation - grabbing individual values

lab1      china
lab3    senegal
dtype: object

In [79]:
series_country1[['lab3','lab4']]


lab3     senegal
lab4    tanzania
dtype: object

### operations in series (vectorized operations)


In [81]:
ser_1_vec = pd.Series([100,200,300,400,500],index=['i1','i2','i3','i4','i5'])

In [82]:
ser_2_vec = pd.Series([500,1000,3000,5000,8000],index=['i6','i7','i1','i2','i8'])

In [83]:
ser_3_vec = pd.Series([1000,2000,3000,400,500],index=['i1','i10','i13','i14','i15'])

In [84]:
## add 2 series

ser_1_vec + ser_2_vec

i1    3100.0
i2    5200.0
i3       NaN
i4       NaN
i5       NaN
i6       NaN
i7       NaN
i8       NaN
dtype: float64

In [85]:
ser_1_vec * ser_2_vec

i1     300000.0
i2    1000000.0
i3          NaN
i4          NaN
i5          NaN
i6          NaN
i7          NaN
i8          NaN
dtype: float64

In [86]:
ser_1_vec > ser_2_vec

### the comparison will fail becausee the series objects need to be identically labeled. meaning the indexes need to be the same

ValueError: Can only compare identically-labeled Series objects

In [5]:
ser_3_vec = pd.Series([99,299,399,499,9],index=['i1','i2','i3','i4','i5'])

In [4]:
ser_4_vec = pd.Series([101,10,20,50,11],index=['i1','i2','i3','i4','i5'])

In [6]:
ser_3_vec > ser_4_vec

i1    False
i2     True
i3     True
i4     True
i5    False
dtype: bool

In [10]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) and (ser_3_vec['i3'] < ser_4_vec['i4'])

False

In [12]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) or (ser_3_vec['i3'] < ser_4_vec['i4'])

True

In [14]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) != (ser_3_vec['i3'] < ser_4_vec['i4'])

True

# Data Frames in Pandas

- Data frames are 2d data structures .
- Data is aligned in a tabular format consists of rows and columns
- DataFrames can hold multiple data types

- DataFrames Constructor in pandas is
        pd.DataFrames(data=,index=,dtype=,copy)
       
        data holds the data source
        index holds the index to access the data source
        dtype is type of the data
        copy is self to false default. take a copy


In [26]:
import numpy as np
import pandas as pd

In [16]:
#from numpy.random import randn

In [18]:
np.random.seed(101)   #### this statement gets us the same set of random numbers everytime this notebook session is executed

In [25]:
myrandom_data = randn(5,4)
print(myrandom_data)

[[-0.80465151  0.25354804  0.64914775  0.35894053]
 [-1.08047146  0.90239776  0.16178119  0.83302932]
 [ 0.97571968 -0.3882387   0.78331605 -0.70895374]
 [ 0.5868473  -1.62134783  0.67753511  0.02610548]
 [-1.67828366  0.3339731  -0.53247053  2.11772738]]


In [23]:
myrandom_data1 = np.random.randn(6,4)

In [24]:
print(myrandom_data1)

[[ 0.39248881  0.22149069 -0.85519604  1.54199041]
 [ 0.66631932 -0.53823463 -0.56858136  1.40733825]
 [ 0.64180551 -0.9050999  -0.39115663  1.02829316]
 [-1.9726051  -0.86688504  0.7207876  -1.22308204]
 [ 1.60677986 -1.11570997 -1.38537856 -1.32966006]
 [ 0.04145994 -0.4110554  -0.7713286   0.11047741]]


In [29]:
#### creating a data frame useing random number generator randn
### we are giubg to use the parameters data, index, columns

mydf = pd.DataFrame(data=myrandom_data, index = ['A','B','C','D','E'], columns=['W','X','Y','Z'])
print(mydf)

          W         X         Y         Z
A -0.804652  0.253548  0.649148  0.358941
B -1.080471  0.902398  0.161781  0.833029
C  0.975720 -0.388239  0.783316 -0.708954
D  0.586847 -1.621348  0.677535  0.026105
E -1.678284  0.333973 -0.532471  2.117727


##### CREATING A DATA FRAME FROM A LIST


In [30]:
df_list = [['a1','b1','c1'],['a2','b2','c2'],['a3','b3','c3']]
print(df_list)

[['a1', 'b1', 'c1'], ['a2', 'b2', 'c2'], ['a3', 'b3', 'c3']]


In [31]:
#### to create user defined index, let us create a list of index
df_index = ['indx1','indx2','indx3']

In [35]:
mylist_df = pd.DataFrame(data=df_list,index=df_index,columns=('ColA','ColB','Colc'))
print(mylist_df)

      ColA ColB Colc
indx1   a1   b1   c1
indx2   a2   b2   c2
indx3   a3   b3   c3
