## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [4]:
import numpy as np

In [2]:
### Numpy Arrays 


In [1]:
### creating a Numpy array from a python list
my_list  = [1.
print(my_list)


[1, 2, 3]


In [2]:
type(my_list)

list

In [4]:
### create numpy array from list my_list
my_num_arr = np.array(my_list)

##print the array
print(my_num_arr)

[1 2 3]


In [5]:
print(type(my_num_arr))

<class 'numpy.ndarray'>


In [6]:
##length of the array
len(my_num_arr)

3

In [7]:
## dimension of the numpy arr
my_num_arr.ndim


1

In [8]:
## for methods that can be used with an array
###  numpyarray name. hit tab


In [9]:
### create a matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix))

<class 'list'>


In [10]:
## create a numpy array from list
my_num_arr2 =  np.array(my_matrix)

In [11]:
my_num_arr2.ndim

2

In [12]:
print(my_num_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### situations where we will need to generate arrays 

## built in methods in numpy

arange - returns evenly spaced values with in a given interval

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
### zeros and ones arrays
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones(3) * 5

array([5., 5., 5.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.ones((5,5)) * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
### generating random integeers

In [5]:
np.random.randint(1,100)

54

In [13]:
np.random.randint(18,25,100)

array([22, 22, 23, 19, 20, 22, 18, 24, 21, 22, 23, 21, 19, 18, 20, 20, 20,
       22, 23, 21, 22, 19, 20, 22, 23, 20, 19, 24, 20, 24, 20, 19, 19, 23,
       23, 19, 18, 21, 21, 18, 19, 21, 22, 23, 23, 22, 19, 22, 18, 22, 21,
       21, 23, 19, 24, 23, 22, 19, 19, 22, 24, 19, 24, 21, 18, 20, 24, 18,
       19, 22, 24, 22, 24, 19, 20, 20, 20, 21, 24, 20, 23, 19, 23, 20, 21,
       21, 19, 22, 23, 23, 19, 24, 20, 21, 22, 20, 20, 19, 21, 24])

In [23]:
print(type(np.random.randint(1,100,10)))

<class 'numpy.ndarray'>


randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(2)

array([-1.10240043, -0.8080607 ])

In [25]:
np.random.randn(5,5)

array([[-0.83685775,  0.28271827,  0.87671666, -1.03797397, -0.91024602],
       [-0.08094697, -0.79001024, -1.77606176,  0.06747947, -1.58132408],
       [ 1.12385355, -1.98541955, -1.2317734 ,  1.70916937,  0.53215474],
       [ 2.57662611, -1.54870965, -1.6826972 , -0.17824522, -1.56055619],
       [ 1.23836042, -1.4968168 , -0.62646138, -0.76240746, -1.51266688]])

Array Attributes

In [26]:
arr = np.arange(25)

In [27]:
arr_new = np.arange(35)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.ndim

1

In [33]:
### reshape
arr_new_reshaped = arr_new.reshape(7,5)

In [32]:
arr_new_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [34]:
print(arr_new_reshaped.ndim)

2


In [50]:
### size of the array
print(print(arr_new_reshaped.size))

35
None


In [51]:
len(arr_new_reshaped)

7

In [29]:
## reshape
arr_reshaped = arr.reshape(5,5)

In [30]:
arr_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr_reshaped.ndim

2

In [53]:
arr.dtype


dtype('int32')

In [54]:
arr_new_reshaped.dtype

dtype('int32')

In [52]:
country_list = ['India','china','Usa','pak']
country_arr = np.array(country_list)
print(country_arr)
print(country_arr.ndim)
print(country_arr.size)
print(country_arr.dtype)

['India' 'china' 'Usa' 'pak']
1
4
<U5


find more information about the formats
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.byteorder.html
https://en.wikipedia.org/wiki/Endianness
https://stackoverflow.com/questions/40589499/what-do-the-signs-in-numpy-dtype-mean

In [57]:
print(country_arr.dtype)

<U5


In [58]:
arr_new_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [60]:
### to get max AND MIN value of a matrix
print(arr_new_reshaped.max())
print(arr_new_reshaped.min())

34
0


In [61]:
## to get the index of the max and min values in a matrix
arr_new_reshaped.argmax()

34

In [63]:
arr_new_reshaped.argmin()    

0

In [ ]:
ranarr1 = np.random.randint(0,50,10)

In [66]:
my_list3 = [[11,22,33],[14,55,60],[7,8,9],[10,200,300],[19,25,29]]
my_matrix1 = np.array(my_list3)
print(my_matrix1)

[[ 11  22  33]
 [ 14  55  60]
 [  7   8   9]
 [ 10 200 300]
 [ 19  25  29]]


In [69]:
my_matrix1.size

15

In [70]:
my_matrix1.ndim

2

In [71]:
my_matrix1.max()

300

In [73]:
my_matrix1.argmax()

11

### INDEXING NUMPY ARRAYS

In [79]:
## indexing one dimensional array
arr5 = np.arange(25)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
arr5_reshaped = arr5.reshape(5,5)
arr5_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr6 = np.arange(0,11)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
### to select a specific element from an array
arr6[7]

7

In [92]:
list7 = [11,22,33,14,55,60,7,8,9,10,200,300,19,25,29]
arr7 = np.array(list7)
print(arr7.ndim)
print(arr7)


1
[ 11  22  33  14  55  60   7   8   9  10 200 300  19  25  29]


In [93]:
arr7[10]

200

In [94]:
arr7[0:5]

array([11, 22, 33, 14, 55])

In [95]:
arr7[0:]

array([ 11,  22,  33,  14,  55,  60,   7,   8,   9,  10, 200, 300,  19,
        25,  29])

In [96]:
arr7[:]

array([ 11,  22,  33,  14,  55,  60,   7,   8,   9,  10, 200, 300,  19,
        25,  29])

In [98]:
arr7[3:8]

array([14, 55, 60,  7,  8])

In [242]:
arr7[4:]

array([ 55,  60,   7,   8,   9,  10, 200, 300,  19,  25,  29])

In [244]:
### multi dimensional arrays
threeD_array = np.arange(27)
threeD_array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [245]:
### to create a 3 dimensional array
threeD_array.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [248]:
fourD_array = np.arange(256).reshape(4,4,4,4)
print(fourD_array)

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]
   [ 12  13  14  15]]

  [[ 16  17  18  19]
   [ 20  21  22  23]
   [ 24  25  26  27]
   [ 28  29  30  31]]

  [[ 32  33  34  35]
   [ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]

  [[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]
   [ 60  61  62  63]]]


 [[[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]

  [[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]]


 [[[128 129 130 131]
   [132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]

  [[144 145 146 147]
   [148 149 150 151]
   [152 153 154 155]
   [156 157 158 159]]

  [[160 161 162 163]
   [164 165 166 167]
   [168 169 170 171]
   [172 173 174 175]]

  [[176 177 178 179]
   [180 181 182 183]
   [184 

In [249]:
fourD_array.ndim

4

###### BROADCASTING

ability to perform operations on all elements of a numpy array and make changes 
permanently changes the values in the array

In [101]:
vararr = np.arange(0,11)

In [102]:
vararr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
## broadcast the value 100 to elements starting index 0 thru index 4

vararr[0:5] = 100
print(vararr)

[100 100 100 100 100   5   6   7   8   9  10]


In [107]:
vararr[0:5] = 120
print(vararr)

[120 120 120 120 120   5   6   7   8   9  10]


In [109]:
vararr[4] = 111
print(vararr)

[120 120 120 120 111   5   6   7   8   9  10]


In [112]:
vararr1 = np.arange(11,25)

vararr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [116]:
### copy slice of vararr into another array called "slice_of_vararr1"
slice_of_vararr1 = vararr1[0:6]
print(slice_of_vararr1)

[11 12 13 14 15 16]


In [117]:
print(vararr1)
print(slice_of_vararr1)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[11 12 13 14 15 16]


In [120]:
### broadcast 99 to all elements in array slice_of_vararr1
slice_of_vararr1[:] = 99
print(slice_of_vararr1)

[99 99 99 99 99 99]


In [121]:
print(vararr1)

[99 99 99 99 99 99 17 18 19 20 21 22 23 24]


In [123]:
### how to change without changing the original array??? 
vararr1_copy = vararr1.copy()
print(vararr1)
print(vararr1_copy)

[99 99 99 99 99 99 17 18 19 20 21 22 23 24]
[99 99 99 99 99 99 17 18 19 20 21 22 23 24]


In [124]:
vararr1_copy[:] = 200
print(vararr1_copy)

[200 200 200 200 200 200 200 200 200 200 200 200 200 200]


In [126]:
vararr1

array([99, 99, 99, 99, 99, 99, 17, 18, 19, 20, 21, 22, 23, 24])

In [130]:
### Conditional statements in numpy
numarr_cond = np.arange(1,11)
print(numarr_cond)
print(type(numarr_cond))
print(numarr_cond.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
int32


In [131]:
numarr_cond > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [132]:
## to know which are the actual values of elements that are greater than 5
## 
bool_array = numarr_cond > 5
print(bool_array)

numarr_cond[bool_array]

[False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [133]:
bool_array1 = numarr_cond < 5
print(bool_array1)

numarr_cond[bool_array1]


[ True  True  True  True False False False False False False]


array([1, 2, 3, 4])

In [135]:
numarr_cond[numarr_cond>5]

array([ 6,  7,  8,  9, 10])

In [136]:
numarr_cond

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
### to find all the elements of array numarr_cond that are even
numarr_cond[(numarr_cond%2 == 0)]

array([ 2,  4,  6,  8, 10])

In [139]:
### to find all the elements of array numarr_cond that are odd
numarr_cond[(numarr_cond%2 != 0)]

array([1, 3, 5, 7, 9])

##### INDEXING WITH 2 DIMENSIONAL ARRAYS

In [151]:
my_new_data = np.arange(100,125)

In [152]:
print(my_new_data)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124]


In [154]:
my_new_data_reshape = my_new_data.reshape(5,5)
print(my_new_data_reshape)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]


In [155]:
### two formats for getting data from a matrix
### double bracket format   arrayname[rownumber][colnumber]
### if i have to get the value "100" which is 1st row and 1st column in the matrix my_new_data_reshape
my_new_data_reshape[0][0]

100

In [156]:
## to get the value "103"
my_new_data_reshape[0][3]

103

In [157]:
### 
my_new_data_reshape[4][4]

124

In [158]:
### extract first row alone
my_new_data_reshape[0]

array([100, 101, 102, 103, 104])

In [160]:
### to extract value 110
my_new_data_reshape[2][0]

110

In [164]:
my_new_data_reshape

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])

In [ ]:
### alternate format for getting data from matrix
### my_new_data_reshape[rowindex,colindex]


In [165]:
my_new_data_reshape[0,0]

100

In [166]:
my_new_data_reshape[2,2]

112

#### Using Slice Notations in Numpy Array Indexing

In [172]:
### extracting first row - row index is 0, row index of 2nd row is 1
my_new_data_reshape[0:1]

array([[100, 101, 102, 103, 104]])

In [175]:
my_new_data_reshape[:1]

array([[100, 101, 102, 103, 104]])

In [179]:
my_new_data_reshape[:1,:]

array([[100, 101, 102, 103, 104]])

In [180]:
mylist = [1,2,50,10,200,300]
mylist[3:5]

[10, 200]

In [182]:
### extract first 2 rows all columns
my_new_data_reshape[:2,:]

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [185]:
### extract first all rows all columns
print(my_new_data_reshape[:5,:])
print('/n')
print('/n')
print(my_new_data_reshape[:,:])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]
/n
/n
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]


In [188]:
### extracting the first column
my_new_data_reshape[0:5,0:1]

array([[100],
       [105],
       [110],
       [115],
       [120]])

In [189]:
my_new_data_reshape[0::,0:1]

array([[100],
       [105],
       [110],
       [115],
       [120]])

In [190]:
my_new_data_reshape[0::,0]

array([100, 105, 110, 115, 120])

In [195]:
### extract 2nd column
my_new_data_reshape[:5,1:2]

array([[101],
       [106],
       [111],
       [116],
       [121]])

In [196]:
### to get the first 2 columns
my_new_data_reshape[:5,0:2]

array([[100, 101],
       [105, 106],
       [110, 111],
       [115, 116],
       [120, 121]])

In [197]:
my_new_data_reshape

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])

In [199]:
### get 111, 112, 113, 114
my_new_data_reshape[2:3,1:5]

array([[111, 112, 113, 114]])

In [201]:
my_new_data_reshape[2,1:5]

array([111, 112, 113, 114])

###  numpy operations and universal functions


In [235]:
my_new_data_reshape[2:3,1:5] * 2

array([[222, 224, 226, 228]])

In [236]:
my_new_data_reshape[2:3,1:5] + 2

array([[113, 114, 115, 116]])

In [203]:
### add
numarr5 = np.arange(125,150)
numarr5

array([125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [204]:
numarr5 + numarr5

array([250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274,
       276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298])

In [206]:
numarr5 + 1

array([126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [207]:
numarr5 * 5

array([625, 630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685,
       690, 695, 700, 705, 710, 715, 720, 725, 730, 735, 740, 745])

In [208]:
numarr5 * numarr5

array([15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689,
       17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164,
       20449, 20736, 21025, 21316, 21609, 21904, 22201])

In [210]:
numarr5 =  (numarr5 * 10)
print(numarr5)

[12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600
 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800
 14900]


In [213]:
### subtraction
print(numarr5 - 10000)

[2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800
 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900]


In [214]:
print(numarr5)


[12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600
 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800
 14900]


In [215]:
numarr5 = numarr5 - 10000
print(numarr5)

[2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800
 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900]


In [218]:
numarr6 = np.arange(5,20)
numarr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [221]:
numarr6_reshaped = numarr6.reshape(5,3)
print(numarr6_reshaped)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [222]:
numarr6_reshaped * 3

array([[15, 18, 21],
       [24, 27, 30],
       [33, 36, 39],
       [42, 45, 48],
       [51, 54, 57]])

In [226]:
numarr6_reshaped = numarr6_reshaped * 3
print(numarr6_reshaped)

[[ 45  54  63]
 [ 72  81  90]
 [ 99 108 117]
 [126 135 144]
 [153 162 171]]


In [227]:
numarr6_reshaped ** 2

array([[ 2025,  2916,  3969],
       [ 5184,  6561,  8100],
       [ 9801, 11664, 13689],
       [15876, 18225, 20736],
       [23409, 26244, 29241]], dtype=int32)

In [228]:
numarr6_reshaped / 6

array([[ 7.5,  9. , 10.5],
       [12. , 13.5, 15. ],
       [16.5, 18. , 19.5],
       [21. , 22.5, 24. ],
       [25.5, 27. , 28.5]])

In [ ]:
### universal array functions

In [229]:
### taking square roots
np.sqrt(numarr6_reshaped)

array([[ 6.70820393,  7.34846923,  7.93725393],
       [ 8.48528137,  9.        ,  9.48683298],
       [ 9.94987437, 10.39230485, 10.81665383],
       [11.22497216, 11.61895004, 12.        ],
       [12.36931688, 12.72792206, 13.07669683]])

In [230]:
### exponential 
np.exp(numarr6_reshaped)

array([[3.49342711e+19, 2.83075330e+23, 2.29378316e+27],
       [1.85867175e+31, 1.50609731e+35, 1.22040329e+39],
       [9.88903032e+42, 8.01316426e+46, 6.49313426e+50],
       [5.26144118e+54, 4.26338995e+58, 3.45466066e+62],
       [2.79934052e+66, 2.26832912e+70, 1.83804612e+74]])

In [231]:
np.sin(numarr6_reshaped)

array([[ 0.85090352, -0.55878905,  0.1673557 ],
       [ 0.25382336, -0.62988799,  0.89399666],
       [-0.99920683,  0.92681851, -0.68969794],
       [ 0.32999083,  0.08836869, -0.49102159],
       [ 0.80640058, -0.97845035,  0.97659087]])

In [233]:
### log of array
np.log(numarr6_reshaped)

array([[3.80666249, 3.98898405, 4.14313473],
       [4.27666612, 4.39444915, 4.49980967],
       [4.59511985, 4.68213123, 4.76217393],
       [4.83628191, 4.90527478, 4.9698133 ],
       [5.03043792, 5.08759634, 5.14166356]])

In [237]:
my_new_data_reshape[2:3,1:5] 

array([[111, 112, 113, 114]])

In [238]:
111 in my_new_data_reshape[2:3,1:5]

True

In [240]:
120 in my_new_data_reshape[2:3,1:5]

False

In [241]:
my_new_data_reshape[2:3,1:5] > 200

array([[False, False, False, False]])